#!/usr/bin/env bash
# shellcheck shell=bash
# E2E harness library for slice gate scripts. SOURCE it, do not execute it. See README.md.
# Nothing is mocked: start_stack boots the real API on a fresh temp DB, the API serves the real built
# web app on the same origin, playwright-cli drives a real browser. The summary and the exit code are
# produced when the script exits. Needs bash >= 4, curl, jq, bun (playwright-cli: BLOCKED without it).

if [ -z "${BASH_VERSION:-}" ] || [ "${BASH_VERSINFO[0]:-0}" -lt 4 ]; then
  echo "e2e lib.sh: bash >= 4 is required (run the gate with 'bash script.sh', not zsh or sh)" >&2
  # shellcheck disable=SC2317  # `exit` is the fallback when this file is not being sourced
  return 1 2>/dev/null || exit 1
fi
if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  echo "e2e lib.sh: source this file, do not execute it" >&2
  exit 2
fi
if [ -n "${_E2E_LIB_LOADED:-}" ]; then return 0; fi
_E2E_LIB_LOADED=1

# --- locations (resolved from this file, so any cwd works) -----------------------
E2E_REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../../.." && pwd -P)"
E2E_WEB_DIR="$E2E_REPO_ROOT/apps/web"

# --- knobs (inputs, overridable from the environment; the library never rewrites them) ---
: "${E2E_WEB:=api}"                 # api: build the web app and let the API serve it | off: API only
: "${E2E_WEB_DIST:=}"               # a prebuilt dist to serve instead of building (never modified)
: "${E2E_API_PORT:=}"               # pin the API port (default: a free port from the kernel)
: "${E2E_API_ENTRY:=$E2E_REPO_ROOT/apps/api/src/index.ts}" # self-test hook, gates leave it alone
: "${E2E_BOOT_TIMEOUT:=30}"         # seconds to wait for the API to become ready
: "${E2E_STOP_TIMEOUT:=5}"          # seconds between SIGTERM and SIGKILL
: "${E2E_HTTP_TIMEOUT:=10}"         # curl --max-time for assert_api / api_get / assert_text url:
: "${E2E_TEXT_TIMEOUT:=5}"          # seconds assert_text polls a live page
: "${E2E_KEEP:=0}"                  # 1 = keep the temp dir after stop_stack
: "${E2E_ALLOW_BLOCKED:=0}"         # 1 = BLOCKED steps do not turn the exit code into 3
: "${E2E_ARTIFACTS_DIR:=}"          # playwright-cli working dir (default: inside the temp dir)
: "${E2E_SESSION:=e2e-$$-$RANDOM}"  # playwright-cli session name, unique per run

# --- state (generated by start_stack, unset by stop_stack: E2E_TMP E2E_API_PID E2E_API_PORT_USED
# E2E_WEB_MODE E2E_WEB_DIST_USED STACK_URL API_URL DB_PATH MEDIA_DIR) -------------------------
E2E_PASS=0 E2E_FAIL=0 E2E_BLOCKED=0
_E2E_DEFERS=() _E2E_PREV_EXIT="" _E2E_FINISHED=0
_E2E_WEB_SEEN="" # topology the summary reports; sticky once a stack ran with E2E_WEB=off
_E2E_PORT_TRIES=3 # API start attempts when the port race is lost

_e2e_err() { printf '[e2e] %s\n' "$*" >&2; }

# --- reporting -------------------------------------------------------------------
pass() { E2E_PASS=$((E2E_PASS + 1)); printf 'PASS     %s\n' "$*"; }
# fail <label> [detail...]: counts a failure and returns 1
fail() {
  local label=${1:-}
  shift || true
  E2E_FAIL=$((E2E_FAIL + 1))
  printf 'FAIL     %s\n' "$label"
  if [ "$#" -gt 0 ]; then printf '%s\n' "$*" >&2; fi
  return 1
}
# blocked <label> <reason>: a step that could not run (external dependency). Never a pass.
blocked() { E2E_BLOCKED=$((E2E_BLOCKED + 1)); printf 'BLOCKED  %s -- %s\n' "${1:-}" "${2:-no reason given}"; }
assert_eq() { # assert_eq <actual> <expected> [label]
  local label=${3:-"expected '$2'"}
  if [ "${1-}" = "${2-}" ]; then pass "$label"; else fail "$label" "  expected: $2"$'\n'"  actual:   $1"; fi
}

# e2e_finish: prints the summary once; E2E_EXIT = 1 on any FAIL, 3 when only BLOCKED, else the script's own code.
e2e_finish() {
  [ "$_E2E_FINISHED" = 1 ] && return 0
  _E2E_FINISHED=1
  local verdict=PASS
  E2E_EXIT=${E2E_EXIT:-0}
  if [ "$E2E_FAIL" -gt 0 ]; then
    verdict=FAIL
    [ "$E2E_EXIT" -ne 0 ] || E2E_EXIT=1
  elif [ "$E2E_EXIT" -ne 0 ]; then
    verdict="ABORTED (script exited $E2E_EXIT before all steps ran)"
  elif [ "$E2E_BLOCKED" -gt 0 ] && [ "$E2E_ALLOW_BLOCKED" != 1 ]; then
    verdict="BLOCKED (not a pass)"
    E2E_EXIT=3
  fi
  # a script that only sourced the library and recorded nothing stays quiet
  if [ $((E2E_PASS + E2E_FAIL + E2E_BLOCKED)) -gt 0 ] || [ "$E2E_EXIT" -ne 0 ]; then
    printf -- '--- e2e summary: %d passed, %d failed, %d blocked, web=%s -- %s\n' \
      "$E2E_PASS" "$E2E_FAIL" "$E2E_BLOCKED" "${_E2E_WEB_SEEN:-$E2E_WEB}" "$verdict"
  fi
}

# --- helpers ---------------------------------------------------------------------
# port_open <port>: exit 0 when something accepts TCP connections on 127.0.0.1:<port>.
port_open() { (exec 3<>"/dev/tcp/127.0.0.1/$1") 2>/dev/null; }

# A free port from the kernel (bind :0, read it back, release; ephemeral ports are >= 32768, clear of
# Chrome's blocked list). Another process can still win it before the API binds: start_stack retries.
_e2e_free_port() {
  bun -e 'const s = Bun.serve({ port: 0, fetch: () => new Response("") }); console.log(s.port); s.stop(true);'
}

_e2e_log_tail() { # <file> [lines]
  [ -s "$1" ] || return 0
  printf -- '--- tail of %s ---\n' "$1" >&2
  tail -n "${2:-40}" "$1" >&2
  printf -- '--- end ---\n' >&2
}

# _e2e_kill <pid>: SIGTERM, wait up to E2E_STOP_TIMEOUT, SIGKILL, reap. Only for a pid start_stack
# recorded (our own child, so the pid cannot have been reused).
_e2e_kill() {
  local pid=$1 deadline=$((SECONDS + E2E_STOP_TIMEOUT))
  if kill -TERM "$pid" 2>/dev/null; then
    while kill -0 "$pid" 2>/dev/null; do
      [ "$SECONDS" -lt "$deadline" ] || { kill -KILL "$pid" 2>/dev/null || true; break; }
      sleep 0.1
    done
  fi
  wait "$pid" 2>/dev/null || true
}

# _e2e_url <path-or-url> <base>: a full URL stays, a path is appended to <base>.
_e2e_url() {
  case $1 in http://* | https://*) printf '%s' "$1" ;; *) [ -n "$2" ] && printf '%s%s' "$2" "$1" ;; esac
}

# --- traps -----------------------------------------------------------------------
# On EXIT: deferred commands (newest first), browser session, stack, previous EXIT trap, summary, exit code.
_e2e_on_exit() {
  local rc=$?
  [ "$BASHPID" = "${_E2E_MAIN_PID:-}" ] || return 0
  trap - EXIT INT TERM HUP
  set +eu # cleanup must run to the end, even under a caller's set -eu
  local i
  for ((i = ${#_E2E_DEFERS[@]} - 1; i >= 0; i--)); do eval "${_E2E_DEFERS[$i]}" || true; done
  if [ -n "${E2E_TMP-}" ] && { [ "$rc" -ne 0 ] || [ "$E2E_FAIL" -gt 0 ]; }; then
    _e2e_log_tail "$E2E_TMP/api.log" 20
  fi
  _e2e_pw_close
  stop_stack
  if [ -n "$_E2E_PREV_EXIT" ]; then eval "$_E2E_PREV_EXIT" || true; fi
  E2E_EXIT=$rc
  e2e_finish
  exit "$E2E_EXIT"
}
_e2e_on_signal() { exit "$1"; } # the EXIT trap then does the cleanup

# e2e_defer <command string>: run at exit, before stop_stack, newest first.
e2e_defer() { _E2E_DEFERS+=("$*"); }

# Installs EXIT/INT/TERM/HUP handling (done when the library is sourced in a non-interactive shell).
# An EXIT trap that already exists is chained: it runs after ours.
e2e_install_traps() {
  _E2E_MAIN_PID=$BASHPID
  local prev
  prev=$(trap -p EXIT)
  if [ -n "$prev" ] && [[ $prev != *_e2e_on_exit* ]]; then
    prev=${prev#trap -- }
    prev=${prev% EXIT}
    # POSIX mode prints `trap -- - EXIT` when no trap is set: "-" is not a command
    [ "$prev" = "-" ] || eval "_E2E_PREV_EXIT=$prev"
  fi
  trap _e2e_on_exit EXIT
  trap '_e2e_on_signal 130' INT
  trap '_e2e_on_signal 143' TERM
  trap '_e2e_on_signal 129' HUP
}

# --- stack lifecycle -------------------------------------------------------------
# Records a FAIL (a script that ignores start_stack's status still exits non-zero), dumps the log, cleans up.
_e2e_start_fail() {
  fail "start_stack" "$*" || true
  if [ -n "${E2E_TMP-}" ]; then _e2e_log_tail "$E2E_TMP/api.log" 40; fi
  stop_stack
  return 1
}

# Ready when: the process is alive AND its log has a `"msg":"listening"` line AND that line announces
# our port (two separate patterns, so key order does not matter) AND GET /health is 200.
# rc: 0 ready | 1 timeout | 2 process died
_e2e_wait_api() { # <pid> <log> <port>
  local pid=$1 log=$2 port=$3 code deadline=$((SECONDS + E2E_BOOT_TIMEOUT))
  while :; do
    kill -0 "$pid" 2>/dev/null || return 2
    if grep '"msg":"listening"' "$log" 2>/dev/null | grep -q "\"port\":$port[,}]"; then
      code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 2 "http://127.0.0.1:$port/health" 2>/dev/null || true)
      [ "$code" = 200 ] && return 0
    fi
    [ "$SECONDS" -ge "$deadline" ] && return 1
    sleep 0.1
  done
}

# The harness OWNS NODE_ENV and BETTER_AUTH_URL for the child (a caller's values are overridden): Better Auth
# fails closed, so only NODE_ENV=development boots without BETTER_AUTH_SECRET (never set or printed here), and
# BETTER_AUTH_URL must be exactly the origin the browser and curl use (API_URL), or its origin check answers 403.
_e2e_launch_api() { # <port>; sets E2E_API_PID (exec: the recorded pid IS the bun process, cwd is the temp dir)
  (cd "$E2E_TMP" && NODE_ENV=development BETTER_AUTH_URL="http://127.0.0.1:$1" PORT="$1" APP_DB_PATH="$DB_PATH" MEDIA_DIR="$MEDIA_DIR" MASTRA_DB_PATH="$E2E_TMP/mastra.db" \
    BACKUP_DIR="$E2E_TMP/backups" WEB_DIST="$E2E_WEB_DIST_USED" exec bun "$E2E_API_ENTRY") >"$E2E_TMP/api.log" 2>&1 </dev/null &
  E2E_API_PID=$!
}

# start_stack: temp dir, built web, the real API on a free port serving it; exports the generated variables.
# Returns 1 after cleanup and a recorded FAIL. Each start makes a fresh temp dir (data does not survive a
# stop). Call it in the main shell, never inside $(...) or a pipeline.
start_stack() {
  local c base=${TMPDIR:-/tmp} attempt port rc
  [ -z "${E2E_TMP-}" ] || { fail "start_stack" "a stack is already running (stop_stack first)" || true; return 1; }
  [[ $E2E_WEB == @(api|off) ]] || { fail "start_stack" "E2E_WEB must be 'api' or 'off', got '$E2E_WEB'" || true; return 1; }
  for c in bun curl jq; do
    command -v "$c" >/dev/null 2>&1 || { fail "start_stack" "'$c' not found in PATH" || true; return 1; }
  done
  E2E_TMP=$(mktemp -d "${base%/}/e2e-stack.XXXXXX") || { unset E2E_TMP; fail "start_stack" "mktemp failed" || true; return 1; }
  E2E_OWNER_PID=$BASHPID
  DB_PATH="$E2E_TMP/app.db"
  MEDIA_DIR="$E2E_TMP/media"
  mkdir -p "$MEDIA_DIR"
  export E2E_TMP DB_PATH MEDIA_DIR
  [ "$_E2E_WEB_SEEN" = off ] || _E2E_WEB_SEEN=$E2E_WEB

  # 1. the web app the API will serve
  if [ "$E2E_WEB" = off ]; then
    E2E_WEB_DIST_USED="$E2E_TMP/web-absent" # nonexistent on purpose: never serve a stale apps/web/dist
    _e2e_err "WARNING: E2E_WEB=off: API only, the web app is NOT served, browser steps cannot pass; the summary says web=off"
  elif [ -n "$E2E_WEB_DIST" ]; then
    case $E2E_WEB_DIST in /*) E2E_WEB_DIST_USED=$E2E_WEB_DIST ;; *) E2E_WEB_DIST_USED="$PWD/$E2E_WEB_DIST" ;; esac
    [ -f "$E2E_WEB_DIST_USED/index.html" ] || { _e2e_start_fail "no index.html in E2E_WEB_DIST=$E2E_WEB_DIST_USED"; return 1; }
  else
    E2E_WEB_DIST_USED="$E2E_TMP/web-dist"
    (cd "$E2E_WEB_DIR" && bun run build --outDir "$E2E_WEB_DIST_USED" --emptyOutDir) >"$E2E_TMP/build.log" 2>&1 ||
      { _e2e_log_tail "$E2E_TMP/build.log" 40; _e2e_start_fail "web build failed"; return 1; }
  fi
  export E2E_WEB_DIST_USED

  # 2. the API on a free port; when the port was not pinned, losing the port race is retried
  for ((attempt = 1; attempt <= _E2E_PORT_TRIES; attempt++)); do
    port=${E2E_API_PORT:-$(_e2e_free_port)}
    [ -n "$port" ] || { _e2e_start_fail "could not pick a free port"; return 1; }
    _e2e_launch_api "$port"
    rc=0
    _e2e_wait_api "$E2E_API_PID" "$E2E_TMP/api.log" "$port" || rc=$?
    [ "$rc" -eq 0 ] && break
    _e2e_kill "$E2E_API_PID"
    unset E2E_API_PID
    if [ "$rc" -eq 2 ] && [ -z "$E2E_API_PORT" ] && grep -qiE 'EADDRINUSE|in use' "$E2E_TMP/api.log"; then
      _e2e_err "port $port was taken before the API bound it; retrying ($attempt/$_E2E_PORT_TRIES)"
      continue
    fi
    _e2e_start_fail "API $([ "$rc" -eq 2 ] && echo 'exited during boot' || echo "not ready within ${E2E_BOOT_TIMEOUT}s") (port $port)"
    return 1
  done
  [ -n "${E2E_API_PID-}" ] || { _e2e_start_fail "API failed to start after $_E2E_PORT_TRIES attempts (port race)"; return 1; }
  E2E_API_PORT_USED=$port
  API_URL="http://127.0.0.1:$port"
  STACK_URL=$API_URL # one origin: the API serves the built web app
  E2E_WEB_MODE=$E2E_WEB
  export E2E_API_PORT_USED API_URL STACK_URL E2E_WEB_MODE
  _e2e_err "stack up: web=$E2E_WEB_MODE STACK_URL=$STACK_URL tmp=$E2E_TMP"
}

# stop_stack: idempotent. Closes the browser session, stops only the API pid start_stack recorded,
# removes the temp dir, unsets every generated variable. Safe from a trap and to call twice.
stop_stack() {
  [ -n "${E2E_TMP-}" ] || return 0
  [ "$BASHPID" = "${E2E_OWNER_PID-}" ] || return 0
  local tmp=$E2E_TMP
  _e2e_pw_close
  if [ -n "${E2E_API_PID-}" ]; then _e2e_kill "$E2E_API_PID"; fi
  unset E2E_TMP E2E_OWNER_PID E2E_API_PID E2E_API_PORT_USED E2E_WEB_MODE E2E_WEB_DIST_USED STACK_URL API_URL DB_PATH MEDIA_DIR
  if [ "$E2E_KEEP" = 1 ]; then _e2e_err "E2E_KEEP=1: leaving $tmp"
  elif [[ $tmp == */e2e-stack.?????? ]]; then rm -rf -- "$tmp"
  else _e2e_err "refusing to remove unexpected path: $tmp"; fi
  return 0
}

# --- browser (playwright-cli) ----------------------------------------------------
pw_available() { command -v playwright-cli >/dev/null 2>&1; }

_e2e_pw_home() { # the working dir of the browser session, or nothing (playwright-cli sessions are per cwd)
  local d=${E2E_ARTIFACTS_DIR:-${E2E_TMP:+$E2E_TMP/pw}}
  [ -n "$d" ] && printf '%s\n' "$d"
}

# Closes this run's browser session (only ever the session named E2E_SESSION), if pw was used.
_e2e_pw_close() {
  local d marker
  d=$(_e2e_pw_home) || return 0
  marker="$d/.e2e-session-$E2E_SESSION"
  [ -e "$marker" ] || return 0
  rm -f "$marker"
  if pw_available; then (cd "$d" && playwright-cli -s="$E2E_SESSION" close) >/dev/null 2>&1 || true; fi
}

# pw <playwright-cli args...>: `playwright-cli -s=<this run's session> --json ...` from the session dir; prints
# the JSON reply. playwright-cli exits 0 even when a command failed, so {"isError":true} becomes status 1;
# a real non-zero status passes through (127 = not installed).
pw() {
  local dir out rc=0
  pw_available || { _e2e_err "pw: playwright-cli not found in PATH"; return 127; }
  dir=$(_e2e_pw_home) || { _e2e_err "pw: no stack is running and E2E_ARTIFACTS_DIR is unset (call start_stack first)"; return 1; }
  mkdir -p "$dir" && : >"$dir/.e2e-session-$E2E_SESSION" || return 1
  out=$(cd "$dir" && playwright-cli -s="$E2E_SESSION" --json "$@" 2>&1) || rc=$?
  printf '%s\n' "$out"
  [ "$rc" -eq 0 ] || return "$rc"
  ! jq -e '.isError == true' >/dev/null 2>&1 <<<"$out"
}

# pw_eval <js expression>: prints the value (strings raw, anything else as JSON). Exit 1 on a JS/CLI error.
pw_eval() {
  local out
  out=$(pw eval "$1") || { jq -r '.error // .' <<<"$out" >&2 2>/dev/null || printf '%s\n' "$out" >&2; return 1; }
  jq -r '.result | (try fromjson catch .) | if type == "string" then . else tojson end' <<<"$out"
}

# pw_open [path-or-url]: opens STACK_URL<path> and records the result. No playwright-cli or no installed
# browser is BLOCKED (never a pass), any other failure a FAIL. Returns 0 only when the page opened.
pw_open() {
  local target out
  target=$(_e2e_url "${1:-/}" "${STACK_URL-}") || target=${1:-/}
  pw_available || { blocked "browser: open $target" "playwright-cli is not installed"; return 1; }
  if out=$(pw open "$target" 2>&1); then
    pass "browser opened $target"
  elif grep -qiE 'not installed|Executable doesn.t exist' <<<"$out"; then
    blocked "browser: open $target" "no usable browser: $(grep -iE 'not installed|Executable' <<<"$out" | head -n1)"
    return 1
  else
    fail "browser: open $target" "$out"
  fi
}

# --- assertions ------------------------------------------------------------------
# api_get <path>: prints the body of a GET on API_URL (curl -f: a non-2xx status is an error).
api_get() {
  local url
  url=$(_e2e_url "$1" "${API_URL-}") || { _e2e_err "api_get: no stack is running (call start_stack first)"; return 1; }
  curl -sf --max-time "$E2E_HTTP_TIMEOUT" "$url"
}

# assert_api <path> <jq-expression> [-X method] [-d body] [-H header]... [-s status] [-l label]
# Passes when the HTTP status is 2xx (or exactly -s) AND `jq -e <expression>` is truthy on the body; on
# failure prints the status and the payload. Options may precede or follow the positionals; `--` ends them.
assert_api() {
  local -a curl_args=() pos=()
  local want="" label="" method=GET
  while [ "$#" -gt 0 ]; do
    case $1 in
      -X | -d | -H | -s | -l)
        [ "$#" -ge 2 ] || { fail "assert_api: $1 needs a value"; return 1; }
        case $1 in -s) want=$2 ;; -l) label=$2 ;; -X) method=$2 curl_args+=(-X "$2") ;; *) curl_args+=("$1" "$2") ;; esac
        shift 2 ;;
      --) shift; pos+=("$@"); break ;;
      -?*) fail "assert_api: unknown option $1"; return 1 ;;
      *) pos+=("$1"); shift ;;
    esac
  done
  [ "${#pos[@]}" -eq 2 ] || { fail "assert_api: usage: assert_api <path> <jq-expression> [options]"; return 1; }
  local path=${pos[0]} expr=${pos[1]} url resp code body jqerr
  label=${label:-"api $method $path :: $expr"}
  url=$(_e2e_url "$path" "${API_URL-}") || { fail "$label" "  no stack is running (call start_stack first)"; return 1; }
  resp=$(curl -s --max-time "$E2E_HTTP_TIMEOUT" ${curl_args[@]+"${curl_args[@]}"} -w $'\n%{http_code}' "$url" 2>/dev/null) || true
  code=${resp##*$'\n'}
  body=${resp%$'\n'*}
  if [ -z "$code" ] || [ "$code" = 000 ]; then fail "$label" "  no response from $url"; return 1; fi
  if { [ -n "$want" ] && [ "$code" != "$want" ]; } || { [ -z "$want" ] && [ "${code:0:1}" != 2 ]; }; then
    fail "$label" "  HTTP $code${want:+ (wanted $want)} from $url"$'\n'"  body: ${body:0:2000}"
    return 1
  fi
  if jqerr=$(jq -e "$expr" <<<"$body" 2>&1 >/dev/null); then
    pass "$label"
  else
    fail "$label" "  jq -e '$expr' was false/null or failed${jqerr:+: $jqerr}"$'\n'"  HTTP $code payload: ${body:0:2000}"
  fi
}

# assert_text <needle> [source]: fixed-string, case-sensitive containment. source (default page):
#   page        document.body.innerText of the live browser page (polled up to E2E_TEXT_TIMEOUT s)
#   title       document.title (polled)
#   eval:<js>   the value of a JS expression on the live page (polled)
#   url:<path>  the raw response body of a GET on STACK_URL<path> (or a full URL); no JS, no polling
assert_text() {
  local needle=${1?assert_text: needle required} src=${2:-page} text="" err="" ok=0 expr url
  local label="text '$needle' in $src"
  case $src in
    url:*)
      if url=$(_e2e_url "${src#url:}" "${STACK_URL-}") && text=$(curl -sf --max-time "$E2E_HTTP_TIMEOUT" "$url" 2>&1); then
        [[ $text == *"$needle"* ]] && ok=1
      else
        err="GET failed: ${text:-no stack is running (call start_stack first)}"
      fi
      ;;
    page | title | eval:*)
      case $src in page) expr='document.body.innerText' ;; title) expr='document.title' ;; *) expr=${src#eval:} ;; esac
      local deadline=$((SECONDS + E2E_TEXT_TIMEOUT))
      while :; do
        if text=$(pw_eval "$expr" 2>&1); then
          err=""
          if [[ $text == *"$needle"* ]]; then ok=1; break; fi
        else
          err=$text
        fi
        [ "$SECONDS" -ge "$deadline" ] && break
        sleep 0.2
      done
      ;;
    *) fail "assert_text: unknown source '$src'"; return 1 ;;
  esac
  if [ "$ok" = 1 ]; then pass "$label"; else fail "$label" "  ${err:-needle not found}"$'\n'"  saw: ${text:0:500}"; fi
}

# sqlite_count <table> [where]: COUNT(*) from the stack's DB (bun:sqlite, read-only). <where> is raw SQL from
# the gate author, e.g. sqlite_count users "email = 'a@b.c'"; no ';' (bun:sqlite silently drops a 2nd statement).
sqlite_count() {
  local table=${1?sqlite_count: table required} where=${2:-} sql
  [[ $table =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || { _e2e_err "sqlite_count: invalid table name '$table'"; return 2; }
  [[ $where != *";"* ]] || { _e2e_err "sqlite_count: the where clause may not contain ';'"; return 2; }
  [ -f "${DB_PATH-}" ] || { _e2e_err "sqlite_count: no database at '${DB_PATH-}' (call start_stack first)"; return 2; }
  sql="SELECT COUNT(*) FROM \"$table\""
  [ -z "$where" ] || sql+=" WHERE $where"
  E2E_SQL=$sql E2E_DB=$DB_PATH bun -e '
    import { Database } from "bun:sqlite";
    const db = new Database(process.env.E2E_DB, { readonly: true });
    db.run("PRAGMA busy_timeout = 5000");
    console.log(Object.values(db.query(process.env.E2E_SQL).get())[0]);
  '
}

if [[ $- != *i* ]]; then e2e_install_traps; fi
